---
- name: install required system packages
  hosts: all
  become: yes
  
  tasks:
  - name: Install required apt system packages
    apt: name={{ item }} state=latest update_cache=yes
    loop: [ 'python3-pip', 'python3-setuptools', 'python-pip', 'python-setuptools', 'docker.io', 'rsync' ]     
  - name: Install Docker Module for Python
    pip:
      name: docker

- name: start Maven container
  hosts: mav
  become: yes
  tasks:
  - name: git clone to machine
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /home/ubuntu/repo/
  - name: start Maven container
    docker_container:
      name: mav
      image: maven:3.3-jdk-8
      volumes: 
      - /home/ubuntu/repo/:/home/user/
      command: mvn package -f /home/user/pom.xml
  - name: copy artefact from maven
    fetch: 
      src: "{{ item }}"
      dest: /home/ubuntu/
    with_fileglob:
      - "/home/ubuntu/repo/*.war"

- name: Launch Tomcat
  hosts: tom
  become: yes
  tasks:
  - name: copy artefact to Tomcat
    copy:
      src: "{{ item }}"
      dest: /home/ubuntu/
    with_fileglob:
      - "/home/ubuntu/*.war"
  - name: start Tomcat container
    docker_container:
      name: 'tomcat'
      image: davidcaste/alpine-tomcat:tomcat8
      volumes: 
      - /home/ubuntu/:/opt/tomcat/webapps/
      ports:
      - "8080:8080"
      command: /opt/tomcat/bin/catalina.sh run