---
- name: install nginx
  hosts: mav
  become: yes
  tasks: 
  - name: install nginx
    apt: 
      name: nginx
      state: latest
  - name: change hellopage
    lineinfile:
      path: /var/www/html
      regexp: '^<h1>Welcome'
      line: <p><script> document.write(new Date().toLocaleDateString()); </script></p>

